/* USER SETTINGS */
export const SET_USER_SETTINGS = 'SET_USER_SETTINGS';

/* PAGE SETTINGS */
export const SET_PAGE_LAYOUT_SUCCESS = 'SET_PAGE_LAYOUT_SUCCESS';
export const SET_PAGE_LAYOUT_REQUEST = 'SET_PAGE_LAYOUT_REQUEST';
export const SET_PAGE_LAYOUT_FAILURE = 'SET_PAGE_LAYOUT_FAILURE';

/*NAV LIST*/
export const PAGE_LIST_SUCCESS = 'PAGE_LIST_SUCCESS';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const SKU_LIST_SUCCESS = 'SKU_LIST_SUCCESS';



export const SET_LAYOUT_SUCCESS ='SET_LAYOUT_SUCCESS';



